name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build API Gateway
      run: |
        echo "Running Build for Gateway Test"
        echo $JAVA_HOME
        cd api-gateway
        chmod +x gradlew
        ./gradlew clean build
        echo "Build complete."
      env:
        JAVA_HOME: ${{ matrix.java_home }}
      strategy:
        matrix:
          java_home: ["/usr/lib/jvm/java-8-openjdk-amd64", "/usr/lib/jvm/java-11-openjdk-amd64"]

    - name: Unit Test
      run: |
        echo "Running unit tests... This will take about 60 seconds."
        cd api-gateway
        mvn test
        echo "Code coverage test complete"

  docker_push:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Push
      run: |
        echo "Running unit tests..."
        cd api-gateway
        docker push evaldas483/applicatus-api-gateway

  # Additional jobs can be added based on your GitLab CI/CD configuration.
